name: Build & Deploy Vulnerable Container

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: acrvulntest                         # without .azurecr.io
      RESOURCE_GROUP: rg-mccptesting
      LOCATION: eastus
      CONTAINER_NAME: vulnapp

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and tag Docker image
        run: |
          IMAGE="$ACR_NAME.azurecr.io/vulnapp:latest"
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push image to ACR
        run: |
          docker push $IMAGE

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --name vulnapp \
            --resource-group myResourceGroup \
            --image myacr.azurecr.io/vulnapp:latest \
            --cpu 1 --memory 1 \
            --registry-login-server myacr.azurecr.io \
            --registry-username $(az acr credential show --name myacr --query username -o tsv) \
            --registry-password $(az acr credential show --name myacr --query passwords[0].value -o tsv) \
            --dns-name-label vulnapp-$RANDOM \
            --ports 80 \
            --os-type Linux \
            --location eastus \
            --restart-policy Never
